# Generated by Django 2.2.13 on 2021-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='Actor',
            field=models.CharField(default='karthi', max_length=60),
            preserve_default=False,
        ),
    ]
